jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.2-node-browsers-legacy
    steps:
      - checkout
      - run: npm install
      - run: bundle install
      - run: ruby './test/circle_ci.rb'